# Generated by Django 3.0.8 on 2020-07-16 03:02

from django.db import migrations
import yap.apps.users.managers


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_is_guest'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', yap.apps.users.managers.UserManager()),
            ],
        ),
    ]
